import Head from 'next/head'
import Link from 'next/link'

export default function Home() {

  return (
    <>
      <Head>
        <title>Better PokeAPI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <center>
      <Link href="/"><h1>Better PokeAPI</h1></Link>
      <div class = "main-menu">
      <div class = "heading">
      <h2>All Endpoints</h2>
      </div>
      <Link href="/random" class = "open-links">Get a random Pokemon</Link>
      <Link href="/name" class = "open-links">Get a Pokemon by name</Link>
      <Link href="/types" class = "open-links">Get a Pokemon by type</Link>
      <Link href="/evolve" class = "open-links">Get a Pokemon's next evolution stage</Link>
      <Link href="/exp" class = "open-links">Get a Pokemon's Experience</Link>
      <Link href="/battle" class = "open-links">Battle two Pokemon</Link>
      <Link href="/catch" class = "open-links">Try to catch a Pokemon</Link>
      </div>
      </center>
    </>
  )
}
